services:
  backend:
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./cra-ai-backend:/app  # Mount source code for live reload

  frontend:
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - ./cra-ai-frontend:/app
      - /app/node_modules