services:
  backend:
    image: ${BACKEND_IMAGE}
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000"
    volumes: []

  frontend:
    image: ${FRONTEND_IMAGE}
    ports:
      - "80:80"
    volumes: []

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - ./cra-ai-frontend/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cra-ai-frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
