services:
  backend:
    build:
      context: ./cra-ai-backend
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./cra-ai-backend:/app
    env_file:
      - ./cra-ai-backend/.env.dev
    expose:
      - "8000"
    depends_on:
      - db
      - mongo
      - redis

  frontend:
    build:
      context: ./cra-ai-frontend
      dockerfile: Dockerfile
    volumes:
      - ./cra-ai-frontend:/app
      - /app/node_modules
    env_file:
      - ./cra-ai-frontend/.env.dev
    expose:
      - "3000"

  db:
    image: postgres:16
    env_file:
      - ./cra-ai-database/.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    env_file:
      - ./cra-ai-database/.env.dev
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  mongo_data:
  redis_data: